### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by parnalte** [steven-murray/hankel#1]
Hello,

In Linux, the installation via pip using `pip install hankel` fails because pip does not find the file "readme.rst". Cloning the GitHub repository and installing using `python setup.py install` works fine in the same Python installation. 

Looking at the source in pypi.python.org I see that the readme file is actually named "README.rst" (note the change of case), and I suspect this may be the problem.

In any case, thanks for this useful package!
Cheers,
Pablo.

**Comment by steven-murray** [comment]
Thank you for letting me know! 

I'm pretty sure I've fixed this now, with #15c5707bca3c595af2d4a1d5e8c6612611a8c0b3 (v0.2.1). Have a try!

**Comment by parnalte** [comment]
Hi,

Yes, the installation works without any issue now. Thanks for the fast answer!
