### ISSUE TITLE
Typos in the examples

### ISSUE THREAD

**Issue by stggh** [steven-murray/hankel#10]
Hi @steven-murray thanks for your very nice work on the Hankel transform. It may prove to be very useful in  providing another image Abel transform method (Fourier-Hankel) for [PyAbel](https://github.com/PyAbel/PyAbel).

I am trying to comprehend the relationship between 1D radial, and 2D coordinate representations, which appear to be covered in the examples, but they do not execute, because of variable name changes/incomplete code.

e.g. the  for the `forward_inverse_transform_hankel_vs_fft.ipynb` notebook,
some of the typos are obvious,
  ```python
  [7]  k_f
  [10] r_f, r_h
```
but I am not sure of the substitutions required for `ll` and `kk` in
```python
  [42]    K2f         = -(kk**2 + ll**2)
```
Would you mind fixing the example code(s)? Tks.

**Comment by steven-murray** [comment]
Hi Steve,


Thanks for trying hankel out.


Sorry about the typos in that example. I've basically re-done the same demo, in the notebook paper_plots.ipynb. It requires v0.3.4 of hankel to run, but it does all run as of today. It may be simpler to follow.


I'll probably remove the previous example soon.


Do let me know if I can help with anything!


Cheers,
Steven

________________________________

**Comment by stggh** [comment]
Thanks! That works. Handy that you are "local". 

I will take a look at the notebook in more detail and get back to you.
