### ISSUE TITLE
SphericalHankelTransform gone?

### ISSUE THREAD

**Issue by tmcclintock** [steven-murray/hankel#12]
I have not used `hankel.py` in about a year. At that time I used the object `SphericalHankelTransform` but it appears that this has been removed. On the readthedocs page there is no indication for the right way to replace this. Do I just set `nu=0.5` or is there a proper way to duplicate this functionality?

**Comment by steven-murray** [comment]
Yes, I took out ``SphericalHankelTransform`` as it was really redundant. I think what you need is ``SymmetricFourierTransform`` with ``ndim=3``. Conversely, if you really don't want the normalisations that come with the analog to the Fourier Transform, you could use ``HankelTransform`` with ``nu=0.5``.
