### ISSUE TITLE
[Question] How to use hankle library for the Laplace Transform of 2D data?

### ISSUE THREAD

**Issue by qm-intel** [steven-murray/hankel#122]
Hi @steven-murray. I am wondering how to use hankle package for the Laplace Transform and Inverse Laplace Transform for the 2D image data using your package. 

Consider we have a sequence of input $`X \in \mathbb{R}^{N\times D}`$, where $`N`$ is the sequence length of N samples (i.e., visual tokens here) and $`D=256`$ is the dimension of embedding.  The embeddings are obtained from a two-layer convolutional neural network.  For example, $N=16$ ($N$ is the number of patches (tokens) in the following image, and each patch is sent to the CNN to obtain an embedding dimension of 256: 
![download](https://github.com/steven-murray/hankel/assets/109509321/b5a4be9e-63b5-4a2c-9f2d-5f627dbef7c4)

In the Fast Fourier transform-based the input $`X`$ is computed in the frequency domain pytorch implementation as follows:

```
# x: the token features, B x H x W x D (where N = H * W), B is batch size
# K: the frequency-domain filter, H x W_hat x D (where W_hat = W // 2 + 1)
X = rfft2(x, dim=(1, 2))
X_tilde = X * K
x = irfft2(X_tilde, dim=(1, 2))
```
My question is how to obtain the Laplace Transform using hankle? is it possible?

**Comment by steven-murray** [comment]
Hi @qm-intel I don't think `hankel` is the right package for this: the Hankel transform is the fourier transform of a function that is *symmetric* in the non-radial dimensions (i.e. for you would be circularly-symmetric). However, your images are not such functions.

**Comment by qm-intel** [comment]
@steven-murray Thanks for the reply
