### ISSUE TITLE
Make the package citable

### ISSUE THREAD

**Issue by MuellerSeb** [steven-murray/hankel#14]
Hi,

I really like your package and i'd like to use and cite it. What do you think about making a doi on zenodo.org (works great with github releases)?

And you will also get a doi-badge for the Readme ;)

Greetings,
Sebastian

**Comment by steven-murray** [comment]
Sounds like a great idea, I'll do that !
________________________________

**Comment by steven-murray** [comment]
Done now, find the badge on the README!
