### ISSUE TITLE
pypi archive does not contain tests and license

### ISSUE THREAD

**Issue by scarabeusiv** [steven-murray/hankel#19]
Could you please add MANIFEST.in file and make sure the LICENSE file is shipped on pypi.

Also with tests we could later safeguard against regressions in our distribution packages if we update some dependency of hankel that would break it in our enviroment. Alternatively fixing issue #18 would allow us to download github archive containing everything.

**Comment by steven-murray** [comment]
In 40c6421477766a9d3d94d46011495176152c49f5 I've added a manifest.in which includes the readme, license and tests. I guess this will only take effect on the next version of hankel, but in the meantime I've also fixed #18 . 

I've opened issue #20 to prompt some packaging updates, so please comment there if you have any specific suggestions for how to better package the library (I don't have much experience with the latest tools/practices for packaging)!
