### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by steven-murray** [steven-murray/hankel#20]
The packaging for this repo is pretty ancient. It could be updated to use something like poetry or pipenv -- something more automated than what it is being done now.

**Comment by MuellerSeb** [comment]
In addition a conda package would be nice, which should be quite easy with [conda-forge](https://conda-forge.org/docs/maintainer/adding_pkgs.html).

**Comment by MuellerSeb** [comment]
I could provide a TravisCI workflow I am using for all my packages. [Example](https://github.com/GeoStat-Framework/ogs5py/blob/44093e73b45e0b14a51a71515dc25ef92a6bb599/.travis.yml)

It is using [cibuildwheel](https://github.com/joerick/cibuildwheel) to create the wheels, which is then easily extendable if there will be cython-code included somewhere in the future. (See this [example](https://github.com/GeoStat-Framework/pentapy/blob/b59a29563938188c4328f98494d8cd453dd9e16e/.travis.yml) for building wheels on win/linux/macOS for py35-py38)

Cheers,
Sebastian

**Comment by MuellerSeb** [comment]
I just created a pull-request on conda-forge to add a recipe for the hankel package.
I added you @steven-murray as a maintainer.

To confirm that you are willing to maintain the hankel-feedstock, you have to leave a comment in the pull-request: https://github.com/conda-forge/staged-recipes/pull/10156

Maintaining only means, that after a new version of hankel is released on pypi, someone has to increase the version number in the recipe. ;-)

The recipe was simply created with:

    conda skeleton pypi hankel

Afterwards I just added a description, the Licence file link and I updated the dependency list.

I hope it is ok for you, that I just created this PR, but I need the hankel package for a release of my own!

Cheers,
Sebastian

**Comment by MuellerSeb** [comment]
Since there was no reply yet, I removed you as a maintainer. So less work for you ;-)
If you want to be added to the maintainer list again, just contact me.

Cheers,
Sebastian

**Comment by steven-murray** [comment]
Hi @MuellerSeb , sorry for the lack of reply -- somehow all Github notifications had stopped being sent to my email for the last... who knows how many weeks?! I've been checking more active repositories manually anyway, so I didn't notice. I fixed it now. 

If it's still possible, I can be added as a maintainer on the conda-forge package! Thanks for setting this up -- I've never done a conda-forge package before (though I use them a fair bit).

**Comment by MuellerSeb** [comment]
Hey @steven-murray , no problem. I will add you through a pull-request with the next release.

For now, ``hankel`` got its conda release, hurray!

https://github.com/conda-forge/hankel-feedstock
https://anaconda.org/conda-forge/hankel

Cheers,
Sebastian

**Comment by steven-murray** [comment]
Awesome, thanks! How is the process of maintaining/updating requirements etc. for a `conda` package? Is it better than standard `environment.txt` etc.? 

Wanting to be able to install `hankel` in `conda` environments is one of the main reasons I haven't moved to using `poetry` or `pipenv` (along with the rate of change of projects like that recently).

**Comment by MuellerSeb** [comment]
Hey there, updating and maintaining is quite simple. There is a bot checking for new pypi releases. If a new release is on pypi, a PR is opened automatically with an updated recipe. In most cases this can just be merged. With the next version, I will add you as maintainer.

**Comment by steven-murray** [comment]
Perfect, thanks!

**Comment by MuellerSeb** [comment]
You are now added as a maintainer to the conda-forge feedstock:
https://github.com/conda-forge/hankel-feedstock

The 1.0.0 version is now release on anaconda:
https://anaconda.org/conda-forge/hankel
