### ISSUE TITLE
problems running examples

### ISSUE THREAD

**Issue by francispoulin** [steven-murray/hankel#3]
First, thanks a lot for putting together this library.  I am very keen to learn how it works and use it. 

Unfortunately, I am having some problems running the examples and notebooks.  Is there an update that means the examples shouldn't run?

1)  When I try the following I get an error that it does not recognize integate.  If I switch integarte to transform that works, so I suppose that's what the new version does?

```
from hankel import HankelTransform
h = HankelTransform(nu=0,N=120,h=0.03)  #Create the HankelTransform instance
f = lambda x : 1   # Create a function which identically 1.
h.integrate(f)    # Should give (1.0000000000003544, -9.8381428368537518e-15)

```
2) When I try and compute the transform of a function to get the spectral version I have a problem

```
from hankel import HankelTransform
import numpy as np
f = lambda x : x/(x**2 + 1)
h = HankelTransform(nu=0,N=120,h=0.03)  #Create the HankelTransform instance
k = np.logspace(-1,1,50)        # Create a log-spaced array of k from 0.1 to 10.
h.transform(f,k,ret_err=False) # Return the transform of f at k.

```
The error is 

TypeError                                 Traceback (most recent call last)
<ipython-input-5-534b1746bc23> in <module>()
      4 h = HankelTransform(nu=0,N=120,h=0.03)  #Create the HankelTransform instance
      5 k = np.logspace(-1,1,50)        # Create a log-spaced array of k from 0.1 to 10.
----> 6 h.transform(f,k,ret_err=False) # Return the transform of f at k.

TypeError: transform() got multiple values for keyword argument 'ret_err'

3) When I tried one of the notebooks, stepsizes_for_fourier, it doesn't seem to be able to import the following:

`from hankel import SymmetricFourierTransform
`

I am happy to try things out if that would help.

Francis

**Comment by steven-murray** [comment]
Hi Francis,

Thanks for giving hankel a try!

I think you have an old version. Try "pip install hankel --upgrade" and it should give you version 0.3.0, for which those examples will work (hopefully!)

Do let me know if they work or not.

Cheers,
Steven

**Comment by francispoulin** [comment]
Hello Steven,

You were correct.  Sorry that I didn't think of trying that myself.

I am happy to say that the library is working beautifully.  I just tested the transform of 1/x and the error is 1e-12.  So much better than using simple numerical integration, which is what I had tried myself.

Thanks a lot for the great library and help!

Francis

**Comment by steven-murray** [comment]
Hi Francis,

No worries, glad it's all working now!

Cheers,
Steven
