### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by steven-murray** [steven-murray/hankel#31]
The version should be bumped to v1, probably after #20 is updated. Install instructions on README can also be updated to include `conda`.

**Comment by MuellerSeb** [comment]
I will add you as maintainer to the conda-forge feedstock with this version-bump.

**Comment by MuellerSeb** [comment]
When do you plan to release? If you need help with the new CI workflow, I can help.
Sebastian

**Comment by steven-murray** [comment]
Ahhh, yes I do need to actually do this. OK I've carved out some time in my schedule for next Thursday. It should be a fairly easy thing, right?

**Comment by MuellerSeb** [comment]
There should be 3 Steps:
1. make a version bump by updating
  https://github.com/steven-murray/hankel/blob/31cf3c0527b821e553d65a33ee966b9f871e5882/hankel/__init__.py#L33
  to `__version__ = "1.0.0"`
2. make a new release on Github with tag "v1.0.0". Then everything should be done automatically and the new version should come up on pypi and zenodo (Maybe you could add me as author to this version on zenodo)
3. update again to `__version__ = "1.0.1.dev0"`, so the next development version starts in the repo.

That should be all. ;-)

**Comment by steven-murray** [comment]
Awesome. OK, I think I'm going to switch to using `setuptools_scm` for versioning, so I don't have to worry about the manual bumping. And I need to add some stuff to the README. Other than that, should be quick.

**Comment by MuellerSeb** [comment]
Sounds cool. I have no experience with `setuptools_scm`. But let's see how this works out.

**Comment by steven-murray** [comment]
The PR for version 1 is #36. I've also added a bunch of linting checks. I've invited you as a collaborator, so I can get your review on some of the PRs!

**Comment by MuellerSeb** [comment]
Cool. Thanks for the shown confidence.

**Comment by MuellerSeb** [comment]
For some reason, the deploy stage was not started, so the v1 release is not showing up on pypi...

**Comment by steven-murray** [comment]
Hmmm. Strange. The condition for that is: ``if: (NOT type IN (pull_request)) AND (branch = master) AND (tag IS PRESENT)``. Does Travis even get run after you merge a PR?

**Comment by MuellerSeb** [comment]
Yes, it also runs on tags:
https://travis-ci.com/github/steven-murray/hankel/builds/153937410

I'll come up with a patch for the `.travis.yml`.

**Comment by MuellerSeb** [comment]
I checked the condition for the `deploy` stage with

    travis-conditions parse "(NOT type IN (pull_request)) AND (branch = master) AND (tag IS PRESENT)"

and it should be ok.. maybe travis got confused, because the `lint` stage was not listed in `stages`

**Comment by MuellerSeb** [comment]
#37

**Comment by MuellerSeb** [comment]
For the time being, you could upload sdist and wheel from here:
https://test.pypi.org/project/hankel/1.0.0/#files
to pypi.

I also noticed, that the auto-generated version for dev versions is non-compliant with test.pypi:
https://travis-ci.com/github/steven-murray/hankel/jobs/299525798#L367

We should include a fix like this:
https://github.com/pypa/setuptools_scm/issues/342

Example:
https://github.com/arokem/pyAFQ/commit/6164a8593ca57be7b1361ba788f109fd29fc4b7e

**Comment by steven-murray** [comment]
Thanks for the link to the 1.0.0 files, I've uploaded them.

I disagree with removing the local part of the version -- I like knowing that the version I'm using is not a release, if I'm using it locally (or as downloaded from github). We shouldn't be uploading to PyPI on non-releases anyway, right? Am I missing something?

**Comment by steven-murray** [comment]
Also, looks like the fix in #37 didn't get the deploy stage to fire...

**Comment by MuellerSeb** [comment]
Guess I found it:
https://stackoverflow.com/a/54930724/6696397

the `branch = master` is not evaluating to true, since the branch holds the tag-name (This is some kind of misbehavior by travis I'd say)

I'll go for another fix.

On the local-version issue:
I think something like `1.0.2.dev1` is better then `1.0.1.dev1+g006a40c` where the commit-hash is added. So you still know it's not a release, since the `devX` part is added.
Let's add both fixes in a PR.

**Comment by MuellerSeb** [comment]
With #38 this could be finally resolved. I accidentally created a `hankel 1.0.2.dev3` release on PyPI:
https://pypi.org/project/hankel/1.0.2.dev3/

You need to delete it. Sorry for that. 
I now skipped the checking for the master branch, which means, if a tag was created on an other branch than master, there will be a release on PyPI. I don't think that this could be a problem, but we should keep that in mind.

**Comment by MuellerSeb** [comment]
You could also add me "sebastian.mueller" as a maintainer to the pypi project, so I could care about that myself in the future.

**Comment by MuellerSeb** [comment]
And can you have a look at readthedocs? I think the doc there is not up-to-date. Maybe this is also a version-issue...

**Comment by MuellerSeb** [comment]
I just updated the conda-forge recipe, added you as a maintainer and adopted the setuptools_scm workflow.
In doing so, I noticed that we introduced setuptools as a runtime dependency, that is not mentioned in the setup.py.
I create an Issue for that. See: #39 

I would suggest to write a version file to get the version at runtime without the help of external packages following https://github.com/pypa/setuptools_scm/tree/v3.4.0#configuration-parameters.
I added a fix to my open PR #38 

What do you think about that?

**Comment by MuellerSeb** [comment]
Cool. Most things resolved and I think we came up with a high quality code package.
Two things remaining:
- What about the doc?
- Could you also create a "release" (not only a tag) so Zenodo will take notice of the new version?

**Comment by steven-murray** [comment]
I'm looking at the doc now. For some reason, it's not being triggered (it last got trigger almost a year ago on master). Do you have an RTD account?

Also not sure about how to create a release... I thought it was automatic when I specified a git tag. Is there something else I have to do?

**Comment by MuellerSeb** [comment]
My RTD account: muellerseb

AFAIK: You can create a release online in the Github repo: https://github.com/steven-murray/hankel/releases

So to make it citable we need another version bump, whether we like it or not. :-D

**Comment by steven-murray** [comment]
OK, docs are up to date (the settings were set to building them in Python2.7, which didn't work).

**Comment by steven-murray** [comment]
Release has been made, and is up on zenodo: https://zenodo.org/record/3716472

I didn't have to make another version bump, it seems! I'm wondering if a tag gets automatically converted to a "Release" if it has a prepended "v" (so `v1.2.3` rather than just `1.2.3`)? And if so, does setuptools_scm work with such tags?

**Comment by MuellerSeb** [comment]
I don't know. I always just drafted a new release with a prepended "v". But since it is recommended by github, I think setuptools_scm knows how to deal with it.

Wow. We should open a bottle of champagne! The last 20% have been the hardest again :-D

And we can finally close this issue.

Cheers mate!
