### ISSUE TITLE
Computing transform of a vector instead a lambda function?

### ISSUE THREAD

**Issue by francispoulin** [steven-murray/hankel#4]
I am wondering how easy/difficult it might be to modify the Hankel transform to act on a vector instead of a lambda function.  There is two reasons why I want to do this.

First, if we wanted to verify that the inverse transform of the transform is the original function, it seems like we need to have the transform act on a vector, since that is what comes out after computing the transform.

Second, there are some functions that I'm dealing with that are not necessarily easy to define as a lambda function.

I have looked at the paper that derives the method and it looks complicated.  But if you think it is straightforward I will probably dive in and see if I can do it but if you think it's hard/impossible, than I won't bother.

I thought I'd ask your opinion since you understand the method very well, and I don't yet.

**Comment by steven-murray** [comment]
Hi Francis,

Thanks for your suggestion. I had considered this, but the way to do it is to use splines... i.e. import ``InterpolatedUnivariateSpline`` from ``scipy.interpolate`` and create a spline out of your discrete function, and pass that as ``f`` to ``hankel``. I'd rather leave this machinery up to the user, who may want to change how they define the spline slightly.

I don't think there is a way of doing the transformation directly with the vector, because you need to know the integrand exactly at certain values defined by the zeros of the Bessel function. Some interpolation between discrete points is thus required.

I hope that helps!
```

**Comment by francispoulin** [comment]
That is a great help!  

I will try and use splines like you suggest.  If I get anything interesting, like proving that the forward and inverse transforms yield the identity I will let you know.  

Today I'm going to compare the zeroth Hankel transform with the 2D Fourier transform to show that they are equal.  

If any of these are examples you might want to include please let me know and I would be happy to put something together.

**Comment by steven-murray** [comment]
Hi Francis,

No worries. I have done these examples myself for a variety of functions, and ensured that hankel works. However, I'd be very happy to see your examples, and perhaps include them as proper examples in the code docs. 

You do need to be careful when doing the forward/inverse transforms to select a large enough range/resolution in k and its dual. 

In fact, you should have a look at some of the tests included in the code repo. Particularly the ``test_round_trip.py`` which does the forward+backward transform for power-law f. You'll notice in that file that many of the potential tests are commented out, and that's because they are non-converging integrals in principle. I should probably just remove them from the file.

Anything interesting pops up, do let me know!

Cheers,
Steven

**Comment by francispoulin** [comment]
Hello Steven,

Thanks for pointing me to your example, that does make it so much easier. 

When I tried doing the inverse transform I increased the resolution and could get something that agrees for a wide range but disagrees around zero.   See below.

I then tried this on another function which is Gaussian like and that worked much better so I guess it depends a lot on the function and one needs to tweak it appropriately.

An example that I put together is to compare the Hankel transform to the 2D Fourier transform. Again, for the Gaussian like example they agree very well.  I haven't done any timings but I imagine the 1D transform is much faster than the 2D.  Not very exciting but I was happy to see it.

Cheers, Francis


```
import numpy as np
import scipy.special as sp
from hankel import HankelTransform
from scipy.interpolate import InterpolatedUnivariateSpline as spline

# Compute the Hankel transform
f = lambda x : 1/x
h = HankelTransform(nu=0,N=1000,h=0.005)  #Create the HankelTransform instance
k = np.logspace(-3,2,100)        # Create a log-spaced array of k from 0.1 to 10.
hspec = h.transform(f,k,ret_err=False) # Return the transform of f at k.

r = np.linspace(1e-2,1,1000)
hspec_sp = spline(k, hspec)
f_new = h.transform(hspec_sp, r, False, inverse=True)

plt.semilogy(r,f(r),'-b',linewidth=2,label='old')
plt.semilogy(r,f_new,'-r',linewidth=2,label='new')
plt.legend(loc='best')
plt.axis('on')
plt.show()
```

**Comment by steven-murray** [comment]
Hi Francis,

This is a really good example. I think for the next version I'll include some sphinx docs, and use something like this in a Jupyter notebook as an example. Could you do this up in a notebook with a bit more commentary as a standalone example?

**Comment by francispoulin** [comment]
Hello Steven,

I agree that notebooks are the way to go.

I just submitted a suggested change.  I added a folder called demo that has two notebooks.  One is essentially the example but the other is more involved.  It computes the Laplacian and tries to invert the Laplacian using the Hankel and Fourier transforms. The latter doesn't work for the Hankel transform.  If you have any ideas as to why not I would be very curious to hear them.

Maybe tomorrow with a friend mind I will have a fresh perspective.

Cheers, Francis

**Comment by francispoulin** [comment]
Hello Steven,

I figured out my major problem.  I was considering a wavenumber for the Hankel transform that is too small.  When I increase it to the smallest wavenumber that fits in the domain things work very nicely.

I will polish it off some more and resubmit it but I do have one more question.  When I compute the transforms (Fourier and Hankel) I get that they are off by 1000 or so. Do you happen to know what the exact scaling factor is?  If not it's no big deal but I thought that might tighten things up a little.  

Cheers, Francis

**Comment by francispoulin** [comment]
Hello Steven,

I updated the notebook but not sure if I need to submit it again in github.  If yes please let me know an I will do that again.  Also, if you have suggestions or thoughts on the notebook please let me know.  I am happy to modify it if you like.

Francis

**Comment by steven-murray** [comment]
Hi Francis,  

Sorry for being out of contact for a while. I'm actually at a conference this week. 

Thanks for the notebook! K so take a good look on Monday and pull it in. 

Cheers 
Steven

**Comment by francispoulin** [comment]
Hello Steven,

Sorry to bother you on your conference, there is no rush.  Actually, I waited a long time before making the fix.

I do have a question for you, only after you return home.  

Do you know if it's possible to compute a radial derivative using a Hankel transform?   I know that we can compute the radial part of the Laplacian, which is what the notebook does, but if we just wanted d/dr it seems a lot harder.  At the moment I am doing this using a 2D fft and it works but it is very expensive and would very much like to do it using Hankel only, if possible.

As I said, no rush!

Cheers, Francis

P.S. I have an idea for a paper in the European Journal of Physics (an undergrad teaching journal) if you wanted to talk about this by email.  I am at fpoulin@uwaterloo.ca.

**Comment by steven-murray** [comment]
Hi Francis,

I have now created a documentation site: http://hankel.readthedocs.io/en/latest/, and your two examples can be found in the examples page on the left menu -- thanks very much!

I was just thinking, for the more complicated demo (with the Laplacian) that it would be useful to really lay out what is going on in the notebook mathematically at the start... I found it pretty difficult to keep up with the intent of what you were doing.

Do you think you could lay it out simply at the top and lead it through a bit more?

I will email you shortly about the idea for the paper.

Cheers,
Steven

**Comment by francispoulin** [comment]
Hello Steven,

Thanks for posting the notebooks.

Sorry that the problem wasn't better presented.  I agree that it jumps straight into it.  I will work on fixing it up an explaining what is really being done and will let you know when I have a more polished version.

Cheers, Francis

**Comment by steven-murray** [comment]
Hi Francis,


No worries at all -- I think it's a really helpful notebook!


Cheers,

Steven

________________________________

**Comment by francispoulin** [comment]
Hello,

I updated the notebook.  Please let me if this is enough or if it needs more.  It was a very good idea to fix this up.

Cheers, Francis
