### ISSUE TITLE
Documentaion bug

### ISSUE THREAD

**Issue by MuellerSeb** [steven-murray/hankel#40]
There is a false default value given for `alt` in the doc-stirng of the SFT:
https://github.com/steven-murray/hankel/blob/166b04e5ac06e2d09dda76b71dcaa8b7f586bc8b/hankel/hankel.py#L395

The actual default value for `alt` is `True`:

https://github.com/steven-murray/hankel/blob/166b04e5ac06e2d09dda76b71dcaa8b7f586bc8b/hankel/hankel.py#L430

**Comment by steven-murray** [comment]
Actually, the default doesn't need to be specified in the docstring, as the
default arguments get written in the signature in the docs. Makes it easier
to keep things consistent.

**Comment by MuellerSeb** [comment]
I totally agree.
