### ISSUE TITLE
[Feature Request] Modified Bessel Function Integration? OR Integration over complex x?

### ISSUE THREAD

**Issue by kpardo** [steven-murray/hankel#45]
Thanks a lot for this package -- I've found it to be really useful lately!

I am currently working on a project that requires integrating over modified Bessel functions (specifically, I_0(x) and K_0(x)). I've tried using Hankel for this, but it requires allowing for integration over J_0(i*x). Is it possible to add this feature? Thanks for all of your work on this package!

**Comment by steven-murray** [comment]
Ah, that's a great idea. You can integrate over `f(i*x)*J_0(x)`, but not over `J_0(i*x)` yet. I'm pretty strapped for time lately, but I do think this is a useful feature to have. It would take me a bit of ramp up time though. 

Do you have ideas for how to go about it, @kpardo ? @MuellerSeb?

**Comment by kpardo** [comment]
@steven-murray I can try my hand at implementing the procedure, if you or @MuellerSeb happen to know where I can find the proper formalism for integrating J_0(i*x). As far as I can tell, the Ogata (2005) formalism doesn't necessarily work for complex arguments.

**Comment by steven-murray** [comment]
Hmmm, thinking about this more, I don't think this is really applicable in `hankel` (at least not in its current scope). `J_0(i*x) = I_0(x)` which is not an oscillating function, and therefore cannot use Ogata's method. It seems like a fundamentally different kind of integral.

**Comment by kpardo** [comment]
Ah good point! Well, thanks for thinking about it!

**Comment by steven-murray** [comment]
Np. Be sure to let me know if anything else can be improved!
