### ISSUE TITLE
Getting the wrong answers for known analytic solutions for Hankel Transforms

### ISSUE THREAD

**Issue by souvikmeister** [steven-murray/hankel#46]
Hi,
I am trying to validate the Hankel transform for this known solution:
![image](https://user-images.githubusercontent.com/65412149/93236996-2132c180-f745-11ea-94fb-93513814c52b.png)
The jupyter notebook code is as follows:
```python
import numpy as np
import matplotlib.pyplot as plt
import math
import hankel
from hankel import HankelTransform     # Import the basic class
print("Using hankel v{}".format(hankel.__version__))

ht1 = HankelTransform(
    nu= 1,     # The order of the bessel function
    N = 9000,   # Number of steps in the integration
    h = 0.0003   # Proxy for "size" of steps in integration
)
r = np.logspace(0, 3); c= 2.57; 
an_j1 = (np.sqrt(c**2 + r**2) - c)/(r*(np.sqrt(c**2 + r**2))); # Analytic Solution

f = lambda x : np.exp(-c*x)
F1 = ht1.transform(f,r,ret_err=False) # Return the J1 transform of f(x) at r.

fig, axes = plt.subplots(1, 1, figsize = (10,5))
fig.suptitle('Hankel Transform Using Guptasarma and Singh Filters')
axes.loglog(r, an_j1, marker = 'o', linestyle = 'None', label = 'J1 Analytic')
axes.loglog(r, F1, marker = '+', linestyle = 'None', label = 'J1 Okata')
axes.set_ylabel('Value')
axes.legend()
axes.grid('both',linestyle = '--')
plt.show()
```
![hankel](https://user-images.githubusercontent.com/19690642/93247620-e190c780-f78e-11ea-91b9-295667bcef2c.png)

As can be seen, the analytic solution and the Hankel transforms don't match. Multiplying F1 by r seems to get it closer but not as accurate at smaller values of r. Seems like I am missing something.

Please help.

Thanks.

Souvik

**Comment by MuellerSeb** [comment]
The hankel transform involves an addition factor `r` in the integral, as shown in the documentation: https://hankel.readthedocs.io/en/latest/demos/getting_started.html#Transforms

Therefore, to get your result, you have to replace the function to transform to:
```python
f = lambda x : np.exp(-c*x) / x
```
Now the additional factor will cancel out and you will get the correct result
![hankel2](https://user-images.githubusercontent.com/19690642/93247865-40eed780-f78f-11ea-92af-be239032340d.png)

Cheers, Sebastian

**Comment by souvikmeister** [comment]
Thank you sebastian .... i suggest including this in the main read the docs .... it wasn't apparent to me. :)

**Comment by MuellerSeb** [comment]
Cool. But this is the common definition of the hankel transform:
https://en.wikipedia.org/wiki/Hankel_transform
![hankel](https://wikimedia.org/api/rest_v1/media/math/render/svg/e4da048303afe7f1ebb93c26ac339e5c96ca37f8)

But there could be a formula displayed at the main page. Fair enough.

**Comment by souvikmeister** [comment]
Yes I think displaying the wikipedia formula on the main page is useful. I can point to multiple books and papers (your read doc page included :) ) where the 'r' term is included as part of f(r) when defining Hankel transform.

**Comment by steven-murray** [comment]
I've made an issue for this in particular. Going to close this one. Thanks for bringing this to our attention, @souvikmeister !

**Comment by souvikmeister** [comment]
Many thanks Steve. Also, is it possible to call normal functions instead of lambda functions ? Of course, I could potentially "nest" a normal function inside the the lambda function, but it would likely save a lot of geophysicists time and trouble if we could simply call regular functions. :)

**Comment by MuellerSeb** [comment]
You can also pass normal functions. They should take one argument, so the `r` can be passed.
