### ISSUE TITLE
[Question] f(m)*J0(r*m) -- can i integrate this with hankel?

### ISSUE THREAD

**Issue by mrkwjc** [steven-murray/hankel#49]
Hi! I have integral of the form:

![F_0(r)=\int_0^{\infty}{f(m)J_0(mr)dm}](https://latex.codecogs.com/svg.latex?\Large&space;{\color{Blue}F_0(r)=\int_0^{\infty}{f(m)J_0(mr)dm}})

Can i solve this with hankel?

Best regards, Marek

P.S. Great work with this package!

**Comment by mrkwjc** [comment]
Ok, obviously I can use `g(m) = f(m)/m` and the Hankel transform gives correct results. Sorry for cluttering...

**Comment by steven-murray** [comment]
Yup! No worries, and thanks for using the package.
