### ISSUE TITLE
Problem with ret_err (even if not declared)

### ISSUE THREAD

**Issue by dparkins** [steven-murray/hankel#7]
I'm getting a problem with the logical test of _ret_err_, even if I don't declare it.

> Traceback (most recent call last):
> File "<stdin>", line 1, in <module>
> File "/Users/uqdpark7/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/hankel.py", line 113, in transform
> if ret_err:
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by dparkins** [comment]
Apologies, pip had not updated correctly. It is now resolved.

**Comment by steven-murray** [comment]
Awesome... always good when things aren't broken :)
