### ISSUE TITLE
problem with resolution in notebook

### ISSUE THREAD

**Issue by francispoulin** [steven-murray/hankel#8]
There is a problem with the first notebook.  

I noticed that in the version that is posted there are 1000 points in r and the transformed field seems to disagree near r = 0. 

However, if I change the number of points to 100, then they seem to agree very well.

# Define grid

r = np.linspace(1e-2,1,100)                       # Define a physical grid
k = np.logspace(-3,2,100)                          # Define a spectral grid

I presume this means that for a given resolution in r, one needs to change some of the parameters, for example the N and h in the transform. 

Do you have any ideas how we should pick these based on dr to ensure that the error in the transformed field is small?

**Comment by steven-murray** [comment]
Hi @francispoulin, has this been resolved to your satisfaction?

**Comment by francispoulin** [comment]
Thanks for asking.

I wish that I had been more specific in my problem (I should learn from this). After looking at all the notebooks i see this is with "testing_forward_and_inverse_transforms".

I have rerun the notebook using the latest master (should I be using something else?) and it still produces results that show the transformed curve has a much larger error near r=0 than for all other points.

Do you see something different?
