### ISSUE TITLE
Invalid constraint on sphinx

### ISSUE THREAD

**Issue by Mietzsche81** [steven-murray/hankel#80]
# Description

Including `hankel` to a poetry project directly or by proxy results in persistent error messages. Caused by an error in the line below:

https://github.com/steven-murray/hankel/blob/2fb1c2e41d2783e0cb66fecf7e9fa03a405c038d/setup.cfg#L48

# Dependencies

# Steps to reproduce

In any existing or new poetry project, add via
```poetry add hankel```

or by adding any project PyPI that depends on `hankel`

Results:
```
Invalid constraint (sphinx (>=2.0<3) ; extra == 'dev') found in hankel-1.2.1 dependencies, skipping
Invalid constraint (sphinx (>=2.0<3) ; extra == 'docs') found in hankel-1.2.1 dependencies, skipping
```

# Suggested fix

`sphinx^2.0`

**Comment by s-t-e-v-e-n-k** [comment]
Versions have to be separated by , so this is getting evaluated as a version of "2.0<3", which doesn't comply with PEP 440 or PEP 508. Sphinx < 3 is also fairly old at this point, so I'd suggest >=2.0
